project:
  type: website
  output-dir: docs

website:
  title: "Tyler Widdison"
  navbar:
    right:
      - href: index.qmd
        text: About
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/tyler-widdison
      - icon: youtube
        href: https://www.youtube.com/@tylerwiddison/videos
      - icon: envelope
        href: "mailto:mail.tylerperrywiddison@gmail.com"


format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
