project:
  type: website
  output-dir: docs

website:
  title: "Tyler Widdison"
  navbar:
    left:
      - href: index.qmd
        text: About
      - about.qmd
      - blog.qmd
      - resume.qmd
    right:
      - icon: github
        href: https://github.com/tyler-widdison
      - icon: envelope
        href: "mailto:mail.tylerperrywiddison@gmail.com"

format:
  html:
    theme: materia
    css: styles.css

editor: visual
